main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('create/', CreatTodo.as_view(), name="create"),
    path('detail/<slug:slug>/', DetaiPage.as_view(), name="details"),
    path('delet/<pk>/', DeletPage.as_view(), name="delets"),

]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
     path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class TodoList(models.Model):
	COLORS = (
		('bg-danger','danger'),
		('bg-warning','warning'),
		('bg-info','info'),
		('bg-success','success'),
		)
	title = models.CharField('Title',max_length=250)
	body = RichTextField()
	date = models.DateTimeField('Date', auto_now_add=True)
	prioroty = models.CharField('Prioroty',max_length=50, choices=COLORS)
	star = models.BooleanField('Star/Unstar', default=False)
	image = models.ImageField( 'Rasim qo\'shish', upload_to='todo_poster/',)

	def __str__(self):
		return self.title

main/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from .models import *

# Create your views here.
class HomeView(ListView):
    model = TodoList

class DetaiPage(DetailView):
    model = TodoList
    slug_field = 'slug'
    template_name = 'detail.html'

class CreatTodo(CreateView):
    model = TodoList
    fields = ['title','body','image','prioroty','star']
    success_url = '/'

class DeletPage(DeleteView):
    model = TodoList
    success_url = '/'

templates/ckeditor/widget.html
<form action="" method="POST">
    {{form.as_p}}
</form>

templates/main/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{object.title}}</title>
</head>
<body>

    <div class="container">
        <img src="{{object.image.url}}" alt="">
        <h4>{{object.title}}</h4>
        <p>{{object.body}}</p>
        <em>{{object.date}}</em>
    </div>
    
</body>
</html> 

templates/main/todolist_form.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="ok">
</form>

templates/main/todolist_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo | List</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">TodoList | Django</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:create' %}">Create</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav><br><br>

      <div class="container">
          <div class="row">
              
              {% for object in object_list %}    
              <div class="col-lg-3">
                  <img src="{{object.image.url}}" alt="">
                  <a href=""><h4>{{object.title}}</h4></a>
                  <p>{{object.body}}</p>
              </div>
              <div>
                  <a href="{% url 'main:delets' main.id %}"></a>
                  <button class="btn btn-danger">
                      delet
                  </button>
              </div>
              {% endfor %}
          </div>
      </div>


    






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>